### ISSUE TITLE
NodeJS, crypto.randomUUID is not a function - doesnt work with nodejs v20.9.0   (Latest LTS: Iron)

### ISSUE THREAD

**Issue by taitruong** [terra-money/wallet-kit#21]
When connecting wallet I get this:

```sh
inpage.js:116631 Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at inpage.js:116631:34
    at new Promise (<anonymous>)
    at Station.connect (inpage.js:116630:16)
    at StationWallet.connect (webpack-internal:///(app-client)/./node_modules/@terra-money/station-wallet/index.js:28:37)
    at async Promise.all (index 0)
    at async connect (webpack-internal:///(app-client)/./node_modules/@terra-money/wallet-kit/useWallet.js:33:44)
```

I had to switch back to node `v18.18.2`   (Latest LTS: Hydrogen)

Check solution here: https://stackoverflow.com/a/73205206/3437868

**Comment by taitruong** [comment]
Problem is not due to node version. It works e.g. using "localhost:3000", but not for "0.0.0.0:3000". Still digging what the issue is.

**Comment by tvl83** [comment]
I have had this issue for a long time. developing locally i use a custom domain and reverse proxy so i dont need the port in the url and i cannot test with station wallet locally because of this issue.
